import React from 'react';
import NavLinks from './ui/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavLinks />
        <div>{children}</div>
      </body>
    </html>
  )
}
